In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [13]:
import yfinance as yf

In [7]:
ruta_excel= './Dataset/datos.xlsx'
tabla = pd.read_excel(ruta_excel)
#tabla

In [8]:
planilla = pd.read_csv('./Dataset/planilla.csv')
planilla.set_index('codigo', inplace = True)
#planilla

In [9]:
# https://drive.google.com/file/d/1yGjTQBG7gGWeJ90m6ExV1OKx4i1aZz1D/view?usp=sharing
id = '1yGjTQBG7gGWeJ90m6ExV1OKx4i1aZz1D'
ruta = f'https://drive.google.com/uc?export=download&id={id}'

archivoG = pd.read_csv(ruta)
#archivoG

In [10]:
rutaGit = 'https://raw.githubusercontent.com/abemen/datasets/refs/heads/main/antropometricas.csv'
antropo = pd.read_csv(rutaGit)
#antropo

In [11]:
otros = pd.read_clipboard()
#otros

In [4]:
otros.to_excel('otros.xlsx', index=False)

In [6]:
contingencia = pd.crosstab(tabla['Edad'], tabla['Sexo'])
contingencia

Sexo  F  M
Edad
18    0  2
19    1  0
20    1  1
21    1  0
22    1  1
23    1  3
25    0  1
26    2  4
27    2  2
28    2  1
29    1  1
30    1  0
31    2  1
32    2  1
33    1  0
34    0  1
35    2  1

In [13]:
n = len(tabla)
intervalos = pd.cut(tabla['Edad'], bins=5)
frecuencias = pd.crosstab(index = intervalos, columns='f')
frecuencias

col_0            f
Edad
(17.983, 21.4]   6
(21.4, 24.8]     6
(24.8, 28.2]    14
(28.2, 31.6]     6
(31.6, 35.0]     8

In [16]:
frecuencias['fa'] = frecuencias['f'].cumsum()
frecuencias['fr'] = frecuencias['f']/n
frecuencias['fra'] = frecuencias['fr'].cumsum()
frecuencias['%'] = frecuencias['fr']*100
frecuencias['%a'] = frecuencias['fra']*100
frecuencias

col_0            f  fa    fr   fra     %     %a
Edad
(17.983, 21.4]   6   6  0.15  0.15  15.0   15.0
(21.4, 24.8]     6  12  0.15  0.30  15.0   30.0
(24.8, 28.2]    14  26  0.35  0.65  35.0   65.0
(28.2, 31.6]     6  32  0.15  0.80  15.0   80.0
(31.6, 35.0]     8  40  0.20  1.00  20.0  100.0

In [20]:
frecuencias.index.categories.mid

Index([19.691499999999998, 23.1, 26.5, 29.9, 33.3], dtype='float64')